name: Build kernel on new version

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'config/**/version'

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    name: Build new kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@main

      - name: Extract branch affected
        id: proxmox-branch
        run: ./scripts/extract_proxmox_branch.sh >> $GITHUB_OUTPUT

      - name: Run build kernel workflow
        uses: ./.github/workflows/build-pve-kernel-container.yml
        with:
          branch: ${{ steps.proxmox-branch.outputs.branch }}
