name: Test Workflow

on:
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  test:
    name: This is a tag test job
    runs-on: ubuntu-latest
    steps:
      - name: Create release tag
        uses: actions/github-script@v6
        env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        with:
          script: |
            const kernelVersion = "6.2.16-99-pve";
            const proxmoxVersion = "8.0";
            const tagName = kernelVersion;
            const taggerName = "Github Actions";
            const taggerEmail = "github-actions@github.com";

            const message = `PVE kernel ${kernelVersion}-relaxablermrr release (Promox ${proxmoxVersion})`;

            const { owner, repo } = context.repo;

            # Create tag object. This is only needed for annotated tags
            await github.git.createTag({ owner, repo, tagName, message, sha,
              "commit", taggerName, taggerEmail });

            # Create tag reference
            const ref = `refs/tags/${tagName}`;
            await github.git.createRef({ owner, repo, ref, sha });
