name: Trigger new pve-kernel release check

on:
  workflow_dispatch:
    inputs:
      save-new-version:
        description: 'Save new detected version'
        type: boolean
        default: true
        required: false
  schedule:
    - cron: '45 2 * * *' # Every day at 2:45AM UTC

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  check-for-new-kernel:
    name: Check for new release for each branch
    strategy:
      fail-fast: false
      matrix:
        branch: ['master', 'pve-kernel-5.15']
    uses: ./.github/workflows/new-pve-kernel-release-check.yml
    with:
      branch: ${{ matrix.branch }}
      save-new-version: ${{ inputs.save-new-version }}
    secrets:
      token: ${{ secrets.PAT }}
    permissions:
      contents: write
